name: Jicofo Container Image

on:
  push:
    branches: [ main ]
    tags: [ 'stable-*-ems*' ]
  pull_request:
    branches: [ main, fosdem ]

env:
  IMAGE_NAME: ${{ github.repository }}/jicofo
  REGISTRY: ghcr.io

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # https://github.com/actions/download-artifact/issues/3
    - name: "Download Jicofo deb"
      run: |
        OTHER_REPO="matrix-org/jicofo"
        WF_NAME="Build deb package"
        ARTIFACT_NAME="debpkg"
        RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow "${WF_NAME}" --json databaseId --jq '.[0].databaseId'`
        gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME} -D jicofo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: "jicofo"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
